version: '3.7'
services:
    app:
        container_name: venturus-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - './node_modules:/app/node_modules'
        ports:
            - '3000:3000'